Reservas\Bundle\ReservasBundle\Entity\pais:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pais:
            type: string
            length: '50'
    oneToMany:
        estado:
            targetEntity: Reservas\Bundle\ReservasBundle\Entity\estado
            mappedBy: pais
        delegacion:
            targetEntity: Reservas\Bundle\ReservasBundle\Entity\delegacion
            mappedBy: pais
        proveedores:
            targetEntity: Reservas\Bundle\ReservasBundle\Entity\usuario
            mappedBy: pais
    lifecycleCallbacks: {  }
