delegacion:
    path:     /
    defaults: { _controller: "ReservasReservasBundle:delegacion:index" }

delegacion_show:
    path:     /{id}/show
    defaults: { _controller: "ReservasReservasBundle:delegacion:show" }

delegacion_new:
    path:     /new
    defaults: { _controller: "ReservasReservasBundle:delegacion:new" }

delegacion_create:
    path:     /create
    defaults: { _controller: "ReservasReservasBundle:delegacion:create" }
    methods:  POST

delegacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReservasReservasBundle:delegacion:edit" }

delegacion_update:
    path:     /{id}/update
    defaults: { _controller: "ReservasReservasBundle:delegacion:update" }
    methods:  [POST, PUT]

delegacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReservasReservasBundle:delegacion:delete" }
    methods:  [POST, DELETE]
