usuario:
    path:     /
    defaults: { _controller: "ReservasReservasBundle:usuario:index" }

usuario_show:
    path:     /{id}/show
    defaults: { _controller: "ReservasReservasBundle:usuario:show" }

usuario_new:
    path:     /{id}/new
    defaults: { _controller: "ReservasReservasBundle:usuario:new" }

usuario_create:
    path:     /create
    defaults: { _controller: "ReservasReservasBundle:usuario:create" }
    methods:  POST

usuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReservasReservasBundle:usuario:edit" }

usuario_update:
    path:     /{id}/update
    defaults: { _controller: "ReservasReservasBundle:usuario:update" }
    methods:  [POST, PUT]

usuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReservasReservasBundle:usuario:delete" }
    methods:  [POST, DELETE]
