vuelos_show:
    path:     /
    defaults: { _controller: "ReservasReservasBundle:vuelos:opcs" }

vuelos_aca:
    path:     /{id}/acapulco
    defaults: { _controller: "ReservasReservasBundle:vuelos:aca" }

vuelos_can:
    path:     /{id}/cancun
    defaults: { _controller: "ReservasReservasBundle:vuelos:can" }

vuelos_cabos:
    path:     /{id}/cabos
    defaults: { _controller: "ReservasReservasBundle:vuelos:cabos" }